### ISSUE TITLE
MigrationScriptError

### ISSUE THREAD

**Issue by mitharris** [cobyism/ghost-on-heroku#131]
The deployment script to Heroku works just fine but when I try to run the project locally, I run into some problems. Specifically, when I run: 

`$  knex-migrator init --mgpath node_modules/ghost`

I receive the following error: 

```
[2017-11-21 14:22:53] ERROR

NAME: MigrationScriptError
MESSAGE: task.up is not a function

level:normal

Error occurred while executing the following migration: 1-create-tables.js
MigrationScriptError: task.up is not a function
    at MigrationScriptError.KnexMigrateError (/Users/tulsa/Apps/labs-www/node_modules/knex-migrator/lib/errors.js:9:26)
    at new MigrationScriptError (/Users/tulsa/Apps/labs-www/node_modules/knex-migrator/lib/errors.js:28:26)
    at /Users/tulsa/Apps/labs-www/node_modules/knex-migrator/lib/index.js:559:19
    at tryCatcher (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

TypeError: task.up is not a function
    at /Users/tulsa/Apps/labs-www/node_modules/knex-migrator/lib/index.js:515:25
    at tryCatcher (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/tulsa/Apps/labs-www/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

Any thoughts on resolving this one?

**Comment by mars** [comment]
Try running `npm install` to get the missing modules.
