### ISSUE TITLE
Unhandled Exception: Error: getaddrinfo

### ISSUE THREAD

**Issue by PandaWhoCodes** [cobyism/ghost-on-heroku#140]
2018-03-16T20:54:06.991506+00:00 app[web.1]: Unhandled rejection Error: getaddrinfo ENOTFOUND mnwax9mxzow0k7hi.cbetxkdyhwsb.us-east-1.rds.amazonaws.com mnwax9mxzow0k7hi.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306
2018-03-16T20:54:06.991553+00:00 app[web.1]:     at errnoException (dns.js:28:10)
2018-03-16T20:54:06.991557+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
2018-03-16T20:54:06.991559+00:00 app[web.1]:     --------------------
2018-03-16T20:54:06.991561+00:00 app[web.1]:     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:145:48)
2018-03-16T20:54:06.991562+00:00 app[web.1]:     at Protocol.handshake (/app/node_modules/mysql/lib/protocol/Protocol.js:52:23)
2018-03-16T20:54:06.991564+00:00 app[web.1]:     at Connection.connect (/app/node_modules/mysql/lib/Connection.js:130:18)
2018-03-16T20:54:06.991565+00:00 app[web.1]:     at /app/node_modules/knex/lib/dialects/mysql/index.js:106:18
2018-03-16T20:54:06.991567+00:00 app[web.1]:     at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:303:9)
2018-03-16T20:54:06.991568+00:00 app[web.1]:     at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:483:18)
2018-03-16T20:54:06.991570+00:00 app[web.1]:     at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)
2018-03-16T20:54:06.991572+00:00 app[web.1]:     at Client_MySQL.acquireRawConnection (/app/node_modules/knex/lib/dialects/mysql/index.js:104:12)
2018-03-16T20:54:06.991574+00:00 app[web.1]:     at Object.create (/app/node_modules/knex/lib/client.js:239:16)
2018-03-16T20:54:06.991576+00:00 app[web.1]:     at Pool._createResource (/app/node_modules/generic-pool/lib/generic-pool.js:354:17)
2018-03-16T20:54:06.991577+00:00 app[web.1]:     at Pool.dispense [as _dispense] (/app/node_modules/generic-pool/lib/generic-pool.js:314:10)
2018-03-16T20:54:06.991579+00:00 app[web.1]:     at Pool.acquire (/app/node_modules/generic-pool/lib/generic-pool.js:436:8)
2018-03-16T20:54:06.991582+00:00 a
pp[web.1]:     at /app/node_modules/knex/lib/client.js:289:19
2018-03-16T20:54:06.991583+00:00 app[web.1]:     at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:303:9)
2018-03-16T20:54:06.991585+00:00 app[web.1]:     at Promise._resolveFromExecutor (/app/node_modules/blue
bird/js/release/promise.js:483:18)
2018-03-16T20:54:06.991587+00:00 app[web.1]:     at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)
2018-03-16T20:54:30.357782+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/" host=pandawhocodes.herokuapp.com request_id=06c37efa-075f-41e6-b0e4-47c4e7865e74 fwd="122.174.18.142" dyno= connect= service= status=503 bytes= protocol=https
2018-03-16T20:54:53.573386+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2018-03-16T20:54:53.573538+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-03-16T20:54:53.717198+00:00 heroku[web.1]: Process exited with status 137
2018-03-16T20:54:53.734313+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by mars** [comment]
Looks like the database is not available.

Is this a new deployment using the default MySQL database (JawsDB Add-on)? If not, how is the database provided?

Maybe the database is simply taking longer than usual to provision. Try `heroku restart` to see if the database has become available.
