### ISSUE TITLE
s3 storage adapter error

### ISSUE THREAD

**Issue by markhillard** [cobyism/ghost-on-heroku#152]
I'm trying to troubleshoot an issue with the s3 storage adapter. I'm getting the following error after the build:

```
Unhandled rejection IncorrectUsageError: We have detected an unknown error in your custom storage adapter.
    at new IncorrectUsageError (/app/node_modules/ghost-ignition/lib/errors/index.js:79:23)
    at Object.getStorage (/app/node_modules/ghost/core/server/adapters/storage/index.js:48:19)
    at setupSiteApp (/app/node_modules/ghost/core/server/web/site/app.js:74:73)
    at setupParentApp (/app/node_modules/ghost/core/server/web/parent-app.js:54:36)
    at /app/node_modules/ghost/core/server/index.js:82:48
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)

/app/content/adapters/storage/s3:1
(function (exports, require, module, __filename, __dirname) { ../../../node_modules/ghost-storage-adapter-s3/
                                                              ^

SyntaxError: Unexpected token .
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.getStorage (/app/node_modules/ghost/core/server/adapters/storage/index.js:32:25)
    at setupSiteApp (/app/node_modules/ghost/core/server/web/site/app.js:74:73)
    at setupParentApp (/app/node_modules/ghost/core/server/web/parent-app.js:54:36)
    at /app/node_modules/ghost/core/server/index.js:82:48
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
```

The build completes successfully, but my site is throwing an application error. When I run `heroku run bash` and then `npm start` I get the above error.

Is there something wrong the the node modules path? I'm a little stuck and can't figure it out. Any help would be appreciated.

**Comment by markhillard** [comment]
I ended up starting from scratch and re-deploying. Works just fine now.
