### ISSUE TITLE
Running ghost locally from heroku install

### ISSUE THREAD

**Issue by hitchcockwill** [cobyism/ghost-on-heroku#23]
I did a clean ghost-on-heroku install and then cloned the repo using ```heroku git:clone -a MYAPP```. I then did a cd to that directory and ran ```npm install --production```. I expected to be able to run ```npm start``` after that, but instead got this error:

```
> ghost-on-heroku@0.6.2 start /Users/willhitch26/Projects/Development/outside-found-ghost
> node server.js


module.js:340
    throw err;
          ^
Error: Cannot find module './lib/express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/willhitch26/Projects/Development/outside-found-ghost/node_modules/ghost/node_modules/express/index.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! ghost-on-heroku@0.6.2 start: `node server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the ghost-on-heroku@0.6.2 start script.
npm ERR! This is most likely a problem with the ghost-on-heroku package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghost-on-heroku
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "/Users/willhitch26/.nvm/v0.10.33/bin/node" "/Users/willhitch26/.nvm/v0.10.33/bin/npm" "start"
npm ERR! cwd /Users/willhitch26/Projects/Development/outside-found-ghost
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/willhitch26/Projects/Development/outside-found-ghost/npm-debug.log
npm ERR! not ok code 0
```

**Comment by cobyism** [comment]
Does it work without the `--production`?

**Comment by hitchcockwill** [comment]
No, no dice without the ```--production```. This SO issue seems to be pretty similar to the problem I'm having. Doing some more investigation now and will update this issue.

http://stackoverflow.com/questions/17162308/node-js-error-cannot-find-module-express

**Comment by hitchcockwill** [comment]
**Update:** The solution for this was to delete the ```node_modules``` directory and run ```npm install``` again.

I'm not sure what the issue was, but that solved the problem for me.

**Comment by cobyism** [comment]
@hitchcockwill Glad to hear you got it sorted out :+1:
